### ISSUE TITLE
Windows directory naming issue for cameras.bin

### ISSUE THREAD

**Issue by andrewmcconnell** [JuliaNeuralGraphics/GaussianSplatting.jl#24]
It seems the file extensions for directories don't convert to windows filepath format. 
At the tutorial instruction line:
julia> GaussianSplatting.gui("C:\\Users\\amokm\\Desktop\\NeuralRadiance\\Chessmen\\dense\\0\\sparse"; scale=1)

ERROR: SystemError: opening file "C:\\Users\\amokm\\Desktop\\NeuralRadiance\\Chessmen\\dense\\0\\sparse\\sparse/0/cameras.bin":
 No such file or directory.

**Comment by pxl-th** [comment]
Should be fixed by latest commit!

**Comment by pxl-th** [comment]
Fixed by https://github.com/JuliaNeuralGraphics/GaussianSplatting.jl/commit/813c0d1f90fab5b373edfef3cb7e932b53dc6ac6
